# Generated by Django 6.0.7 on 2026-08-10 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Expense'), (0, 'Income')])),
                ('bank', models.CharField(max_length=100)),
                ('merchant', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Other'), (1, 'Food'), (2, 'Shopping'), (3, 'Travel')], default=0)),
                ('transaction_at', models.DateTimeField()),
                ('original_sms', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
